### ISSUE TITLE
Can not run in deno v1.0.0

### ISSUE THREAD

**Issue by Yurunsoft** [skoshx/http-server#1]
```
Compile https://raw.githubusercontent.com/SkoshRG/http-server/master/index.ts
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    async read(_: Uint8Array): Promise<number | Deno.EOF> {
                                                     ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:10:54

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'. 
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:11:19

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.       
  async function read(buf: Uint8Array): Promise<number | Deno.EOF> {
                                                              ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:19:63

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (finished) return Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:20:31

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    let result: number | Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:21:31

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (result !== Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:29:25

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async function read(buf: Uint8Array): Promise<number | Deno.EOF> {
                                                              ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:46:63

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (finished) return Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:47:31

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if ((await tp.readLine()) === Deno.EOF) {
                                           ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:59:44

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (line === Deno.EOF) throw new UnexpectedEOFError();
                      ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:66:23

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:76:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:81:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:93:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if ((await tp.readLine()) === Deno.EOF) {
                                           ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:97:44

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if ((await r.readLine()) === Deno.EOF) {
                                        ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:105:41

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:110:19

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  assert(result != Deno.EOF, "trailer must be set");
                        ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:134:25

TS2339 [ERROR]: Property 'toAsyncIterator' does not exist on type 'typeof Deno'.
  for await (const chunk of Deno.toAsyncIterator(r)) {
                                 ~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.35.0/http/io.ts:167:34

TS2345 [ERROR]: Argument of type 'BufWriter' is not assignable to parameter of type 'Reader'.
  Property 'read' is missing in type 'BufWriter' but required in type 'Reader'.
    const n = await Deno.copy(writer, r.body);
                              ~~~~~~
    at https://deno.land/std@v0.35.0/http/io.ts:276:31

    'read' is declared here.
        read(p: Uint8Array): Promise<number | null>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at $asset$/lib.deno.ns.d.ts:203:5

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
): Promise<ServerRequest | Deno.EOF> {
                                ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:346:33

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  if (firstLine === Deno.EOF) return Deno.EOF;
                         ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:349:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  if (firstLine === Deno.EOF) return Deno.EOF;
                                          ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:349:43

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  if (headers === Deno.EOF) throw new UnexpectedEOFError();
                       ~~~
    at https://deno.land/std@v0.35.0/http/io.ts:351:24

TS2339 [ERROR]: Property 'listenTLS' does not exist on type 'typeof Deno'.
const { listen, listenTLS } = Deno;
                ~~~~~~~~~
    at https://deno.land/std@v0.35.0/http/server.ts:16:17

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    while ((await body.read(buf)) !== Deno.EOF) {}
                                           ~~~
    at https://deno.land/std@v0.35.0/http/server.ts:120:44

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    let req: ServerRequest | Deno.EOF | undefined;
                                  ~~~
    at https://deno.land/std@v0.35.0/http/server.ts:141:35

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (req === Deno.EOF) {
                       ~~~
    at https://deno.land/std@v0.35.0/http/server.ts:151:24

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (req === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.35.0/http/server.ts:171:22

TS2339 [ERROR]: Property 'next' does not exist on type 'Listener'.
    const { value, done } = await this.listener.next();
                                                ~~~~
    at https://deno.land/std@v0.35.0/http/server.ts:201:49

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ListenTLSOptions'.
export type HTTPSOptions = Omit<Deno.ListenTLSOptions, "transport">;
                                     ~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.35.0/http/server.ts:252:38

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ListenTLSOptions'.
  const tlsOptions: Deno.ListenTLSOptions = {
                         ~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.35.0/http/server.ts:272:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (rr === Deno.EOF) {
                      ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:85:23

TS2531 [ERROR]: Object is possibly 'null'.
      assert(rr >= 0, "negative read");
             ~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:89:14

TS2531 [ERROR]: Object is possibly 'null'.
      this.w += rr;
                ~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:90:17

TS2531 [ERROR]: Object is possibly 'null'.
      if (rr > 0) {
          ~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:91:11

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async read(p: Uint8Array): Promise<number | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:122:52

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    let rr: number | Deno.EOF = p.byteLength;
                          ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:123:27

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        const nread = rr === Deno.EOF ? 0 : rr;
                                  ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:131:35

TS2531 [ERROR]: Object is possibly 'null'.
        assert(nread >= 0, "negative read");
               ~~~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:132:16

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (rr === 0 || rr === Deno.EOF) return rr;
                                  ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:145:35

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readFull(p: Uint8Array): Promise<Uint8Array | Deno.EOF> {
                                                           ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:172:60

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (rr === Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:177:25

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
            return Deno.EOF;
                        ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:179:25

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readByte(): Promise<number | Deno.EOF> {
                                          ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:194:43

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (this.eof) return Deno.EOF;
                                ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:196:33

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readString(delim: string): Promise<string | Deno.EOF> {
                                                         ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:214:58

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buffer == Deno.EOF) return Deno.EOF;
                       ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:218:24

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buffer == Deno.EOF) return Deno.EOF;
                                        ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:218:41

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readLine(): Promise<ReadLineResult | Deno.EOF> {
                                                  ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:244:51

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    let line: Uint8Array | Deno.EOF;
                                ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:245:33

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (line === Deno.EOF) {
                      ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:278:23

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:279:19

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readSlice(delim: number): Promise<Uint8Array | Deno.EOF> {
                                                            ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:312:61

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
          return Deno.EOF;
                      ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:329:23

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async peek(n: number): Promise<Uint8Array | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:374:52

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:391:19

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (result === Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.35.0/io/bufio.ts:550:25

TS2345 [ERROR]: Argument of type '"a"' is not assignable to parameter of type 'OpenOptions | undefined'.
  const file = await open(filepath, "a");
                                    ~~~
    at https://deno.land/std@v0.35.0/io/util.ts:44:37

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
export const isWindows = build.os === "win";
                         ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.35.0/path/constants.ts:51:26

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
const isWin = Deno.build.os === "win";
              ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.35.0/path/globrex.ts:5:15

TS2349 [ERROR]: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
      path = env()[`=${resolvedDevice}`] || cwd();
             ~~~
    at https://deno.land/std@v0.35.0/path/win32.ts:42:14

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
export function assertNotEOF<T extends {}>(val: T | Deno.EOF): T {
                                                         ~~~
    at https://deno.land/std@v0.35.0/testing/asserts.ts:382:58

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  assertNotEquals(val, Deno.EOF);
                            ~~~
    at https://deno.land/std@v0.35.0/testing/asserts.ts:383:29

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readLine(): Promise<string | Deno.EOF> {
                                          ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:42:43

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (s === Deno.EOF) return Deno.EOF;
                   ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:44:20

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (s === Deno.EOF) return Deno.EOF;
                                    ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:44:37

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readMIMEHeader(): Promise<Headers | Deno.EOF> {
                                                 ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:68:50

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buf === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:74:22

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:75:19

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buf === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:81:22

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (kv === Deno.EOF) throw new UnexpectedEOFError();
                      ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:91:23

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readLineSlice(): Promise<Uint8Array | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:136:52

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (r === Deno.EOF) return Deno.EOF;
                     ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:141:22

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (r === Deno.EOF) return Deno.EOF;
                                      ~~~
    at https://deno.land/std@v0.35.0/textproto/mod.ts:141:39

TS2349 [ERROR]: This expression is not callable.
  Type 'Boolean' has no call signatures.
    return info.isFile()
                ~~~~~~
    at https://deno.land/x/open/index.ts:50:17

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"mac"' have no overlap.
  if (os === 'mac') {
      ~~~~~~~~~~~~
    at https://deno.land/x/open/index.ts:90:7

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
  } else if (os === 'win') {
             ~~~~~~~~~~~~
    at https://deno.land/x/open/index.ts:104:14

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"mac"' have no overlap.
  if (os === 'mac' && appArguments.length > 0) {
      ~~~~~~~~~~~~
    at https://deno.land/x/open/index.ts:140:7

TS2322 [ERROR]: Type '{ args: string[]; stdin: "piped"; stderr: "piped"; stdout: "piped"; }' is not assignable to type 'RunOptions'.
  Object literal may only specify known properties, and 'args' does not exist in type 'RunOptions'.    
    args: [command, ...cliArguments],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/open/index.ts:146:5

TS2349 [ERROR]: This expression is not callable.
  Type 'Boolean' has no call signatures.
    return info.isFile()
                ~~~~~~
    at https://raw.githubusercontent.com/SkoshRG/http-server/master/hooks.ts:48:17

TS2339 [ERROR]: Property 'hostname' does not exist on type 'Addr'.
  Property 'hostname' does not exist on type 'UnixAddr'.
  const ipAddress = req.conn.remoteAddr.hostname ?? '';
                                        ~~~~~~~~
    at https://raw.githubusercontent.com/SkoshRG/http-server/master/hooks.ts:57:41

TS2349 [ERROR]: This expression is not callable.
  Type 'Boolean' has no call signatures.
      return info.isFile()
                  ~~~~~~
    at https://raw.githubusercontent.com/SkoshRG/http-server/master/index.ts:152:19

TS2339 [ERROR]: Property 'name' does not exist on type 'FileInfo'.
      const fileUrl = join(dirUrl, files[i].name ?? '');
                                            ~~~~
    at https://raw.githubusercontent.com/SkoshRG/http-server/master/index.ts:268:45

TS2349 [ERROR]: This expression is not callable.
  Type 'Boolean' has no call signatures.
        <p>${this.modeToString(files[i].isDirectory(), files[i].mode)}</p>
                                        ~~~~~~~~~~~
    at https://raw.githubusercontent.com/SkoshRG/http-server/master/index.ts:271:41

TS2339 [ERROR]: Property 'len' does not exist on type 'FileInfo'.
        <p>${this.formatBytes(files[i].len)}</p>
                                       ~~~
    at https://raw.githubusercontent.com/SkoshRG/http-server/master/index.ts:272:40

TS2339 [ERROR]: Property 'name' does not exist on type 'FileInfo'.
        <a href="${fileUrl}">${files[i].name}</a>
                                        ~~~~
    at https://raw.githubusercontent.com/SkoshRG/http-server/master/index.ts:273:41

Found 86 errors.
```

**Comment by cristiandav** [comment]
Same problem here..

**Comment by epomatti** [comment]
Yep, same here

**Comment by skoshx** [comment]
@evandropomatti @cristiandav @Yurunsoft There were a lot of API changes with Deno v1, will be fixing this and the deno-open repo shortly...
